name:                QCA-STACK
version:             0.1.0.0
github:              "wlambooy/QCA-STACK"
license:             BSD3
author:              "Willem Lambooy"
maintainer:          "willem.lambooij@ru.nl"
copyright:           "2021 Willem Lambooy"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wlambooy/QCA-STACK#readme>

dependencies:
- base >= 4.7 && < 5
- matrix >= 0.3
- mtl >= 2.2.2
- containers >= 0.6.2.1
- timeit >= 2.0
- split  >= 0.2.3.4
- ParserFunction >= 0.1.0
- parsec >= 3.1.14.0

library:
  source-dirs: src

executables:
  QCA-STACK-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QCA-STACK

tests:
  QCA-STACK-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QCA-STACK
